version: 2
updates:
- package-ecosystem: docker
  directory: "/php-alpine"
  schedule:
    interval: daily
    timezone: Europe/Warsaw
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: php
    versions:
    - 8.0.1.pre.fpm.pre.alpine
    - 8.0.2.pre.fpm.pre.alpine
