name: Docker

on:
  push:
    branches:
      - "#2-prepare-cicd"

    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  COMPOSER_VERSION: ${{ secrets.COMPOSER_VERSION }}

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build . --file ./php-alpine/Dockerfile --build-arg COMPOSER_VERSION=$COMPOSER_VERSION

  push:
  
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker build . --file ./php-alpine/Dockerfile --build-arg COMPOSER_VERSION=$COMPOSER_VERSION --tag $IMAGE_NAME
          IMAGE_ID=docker.pkg.github.com/equipment-manager/equipment-manager-environment/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo $IMAGE_ID
          
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.SECRET_TOKEN }}" | docker login docker.pkg.github.com  -u ${{ github.actor }} --password-stdin

      #- name: Push image to GitHub Container Registry
      #  run: |
      #    IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')

      #    docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
      #   docker push $IMAGE_ID:$VERSION